endpoints:
  hypermedia:
    enabled: true
management:
  context-path: /admin
  info:
    app:
      encoding: UTF-8
      java:
        source: 1.8
        target: 1.8
    git:
      mode: full
# This did not work for some reason had to use System.setProperty in Application.class
#hazelcast:
#  jmx: true